### ISSUE TITLE
Nearest Neighbour Interpolation

### ISSUE THREAD

**Issue by JulienDoerner** [LeanderSchlegel/CRPropa3#5]
The Function [`nearestNeigbourInterpolation`](https://github.com/LeanderSchlegel/CRPropa3/blob/351f820b4759590383a9fca7e994c26ad20b4cca/include/crpropa/Grid.h#L510) is only a private function that can not be used by the user and only calls the [`closestValue`](https://github.com/LeanderSchlegel/CRPropa3/blob/351f820b4759590383a9fca7e994c26ad20b4cca/include/crpropa/Grid.h#L315) which is public. Therefor I suggest to leave `nearestNeighbourInterpolation` out and directly use `closestValue` in the `interpolation`. 
I think the only argument to keep it would be that it is easier to read with the seprate function.

**Comment by LeanderSchlegel** [comment]
That is a good suggestion, is done :)
